name = "muso"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Attach the Worker to the custom domain route (top-level)
routes = [{ pattern = "muso.tre.systems/*" }]

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
